import Header from "./components/layout/Header";
import "./globals.css";

export const metadata = {
  title: "panaverse-nextjs-tailwindcss",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
